### ISSUE TITLE
wrong directions for setup in `README.md`

### ISSUE THREAD

**Issue by lalitmee** [ibhagwan/smartyank.nvim#1]
I am not sure, if this is incorrect or not. But please have a look.

![image](https://user-images.githubusercontent.com/10762218/194707341-5a519f25-2e92-4c07-b300-52f8351d5bf6.png)

I think, the code for the `vimscript` should use `require('smartyank')` instead of `require('fzf-lua')`.

Please check.

**Comment by ibhagwan** [comment]
Ty @lalitmee, I copied this part of the README from my other plug-in and missed that :)
