### ISSUE TITLE
Sometimes yank get stuck.

### ISSUE THREAD

**Issue by dhruvinsh** [ibhagwan/smartyank.nvim#3]
Hi,
I am not 100% sure how to debug this issue but when I try to yank sometimes it just get stuck. I can not move around or anything unless I press `C-c` to stop what it is doing then retry the yank it works fine

I am using windows 11 and wsl2 with neovim 0.8.0 and plugin is pin to commit = "66dcb60"

I appreciate any help to debug this issue. Again I am not even sure if it would be issue from this plugin or not.

**Comment by ibhagwan** [comment]
This plug-in is rather simple, it’s just one auto command that does a few things, you can start by disabling some of the functionality selectively and seeing if the issue goes away.

Alternatively you can just copy the autocmd directly to your config piece by piece and see which part is the culprit, if you’re not using it over SSH there isn’t much happening other than highlight on yank (which is just a call to neovim API) and a call to tmux set buffer.

**Comment by ibhagwan** [comment]
Since you mentioned you’re using windows perhaps it’s the call to tmux that makes it stuck since it’s not installed, have you tried disabling tmux?

**Comment by dhruvinsh** [comment]
So I am running WSL2 which is basically virtual Linux right, So I kept the tmux option enable because sometime I do use neovim within tmux. I am away from my system right now but I will definitely give it a try and later update here.

**Comment by dhruvinsh** [comment]
it seems that `xsel` was causing the issue. As soon as I removed it neovim is back to normal. Now it is falling back to `win32yank.exe` on wsl

**Comment by ibhagwan** [comment]
> it seems that `xsel` was causing the issue. As soon as I removed it neovim is back to normal. Now it is falling back to `win32yank.exe` on wsl

You can try `xclip` instead
